using TinyEXR.Native;

namespace TinyEXR
{
    public enum CompressionType
    {
        None = EXRNative.TINYEXR_COMPRESSIONTYPE_NONE,
        RLE = EXRNative.TINYEXR_COMPRESSIONTYPE_RLE,
        ZIPS = EXRNative.TINYEXR_COMPRESSIONTYPE_ZIPS,
        ZIP = EXRNative.TINYEXR_COMPRESSIONTYPE_ZIP,
        PIZ = EXRNative.TINYEXR_COMPRESSIONTYPE_PIZ,
        PXR24 = EXRNative.TINYEXR_COMPRESSIONTYPE_PXR24,
        B44 = EXRNative.TINYEXR_COMPRESSIONTYPE_B44,
        B44A = EXRNative.TINYEXR_COMPRESSIONTYPE_B44A,
        DWAA = EXRNative.TINYEXR_COMPRESSIONTYPE_DWAA,
        DWAB = EXRNative.TINYEXR_COMPRESSIONTYPE_DWAB,
    }
}
