name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-15-intel, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Prepare openexr-images samples
      shell: pwsh
      run: ./Scripts/prepare-openexr-images.ps1

    - name: Test default target
      run: dotnet test --project ./Test/TinyEXR.Test/TinyEXR.Test.csproj --configuration Release --report-trx --report-trx-filename TinyEXR.Test.trx -p:SignAssemblyKey=false

    - name: Test netstandard fallback target
      run: dotnet test --project ./Test/TinyEXR.NetStandardFallback.Test/TinyEXR.NetStandardFallback.Test.csproj --configuration Release --report-trx --report-trx-filename TinyEXR.NetStandardFallback.Test.trx -p:SignAssemblyKey=false
