name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-15-intel, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Prepare openexr-images samples
      shell: pwsh
      run: ./TinyEXR.Test/prepare-openexr-images.ps1

    - name: Build
      run: dotnet build TinyEXR.Test/TinyEXR.Test.sln --configuration Release -p:SignAssemblyKey=false

    - name: Test
      run: dotnet test --solution TinyEXR.Test/TinyEXR.Test.sln --configuration Release --no-build --report-trx --report-trx-filename test-results.trx -p:SignAssemblyKey=false
